name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      - uses: oven-sh/setup-bun@d3603274aca5625baad52ec06108517a089cdd00 # v1
      - run: bun i --frozen-lockfile
      - run: bun run build
